/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class verify_equipment_AntiDebugging */

#ifndef _Included_love_LI
#define _Included_love_LI
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_love_LI_LI
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
